name: backend-Terraform

on: push

jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v1

      - name: Verify Terraform version
        run: terraform --version

      - name: ls
        run: ls

      - name: cd into infra
        run: cd infra

      - name: ls
        run: ls

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        run: terraform apply -auto-approve -input=false
